endpoints:
  - name: "charging-station"
    local:
      port: 14588
    sleep:
      interval: 5
      heartbeat-interval: 2
  - name: "uav"
    local:
      port: 14589
  - name: "clients"
    local:
      ports:
        start: 14591
        end: 14595
  - name: "clients-filtered"
    local:
      ports:
        start: 14596
        end: 14597
    filter:
      type: "drop"
      messages:
        - "SYS_STATUS"
        - "GPS_RAW_INT"
  - name: "broadcast"
    remote:
      ip: "192.168.0.255"
      port: 14600
    broadcast: "discovery"
    sleep:
      interval: 5
      heartbeat-interval: 1
